# Generated by Django 5.2 on 2025-11-12 21:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("hiring", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("position", models.CharField(max_length=200)),
                ("offer_date", models.DateField()),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "completed_sections",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_token",
                    models.CharField(
                        db_index=True, editable=False, max_length=100, unique=True
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "district",
                    models.ForeignKey(
                        help_text="School district this candidate belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_candidates",
                        to="core.schooldistrict",
                    ),
                ),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding",
                        to="hiring.jobapplication",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_candidates",
                "ordering": ["district", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("section_completed", "Section Completed"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed by Admin"),
                            ("document_uploaded", "Document Uploaded"),
                            ("email_sent", "Email Sent"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("section_name", models.CharField(blank=True, max_length=50)),
                ("performed_by_candidate", models.BooleanField(default=False)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "district",
                    models.ForeignKey(
                        help_text="School district this audit log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_audit_logs",
                        to="core.schooldistrict",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="onboarding.onboardingcandidate",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_audit_logs",
                "ordering": ["district", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("i9_document_a", "I-9 List A Document"),
                            ("i9_document_b", "I-9 List B Document"),
                            ("i9_document_c", "I-9 List C Document"),
                            ("certification", "Teaching Certification"),
                            ("license", "Professional License"),
                            ("transcript", "Transcript"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="onboarding_documents/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="onboarding.onboardingcandidate",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        help_text="School district this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_documents",
                        to="core.schooldistrict",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_documents",
                "ordering": ["district", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingEmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("invitation", "Onboarding Invitation"),
                            ("reminder", "Reminder"),
                            ("submission_confirmation", "Submission Confirmation"),
                            ("admin_notification", "Admin Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("sent", models.BooleanField(db_index=True, default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="onboarding.onboardingcandidate",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        help_text="School district this email log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_email_logs",
                        to="core.schooldistrict",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_email_logs",
                "ordering": ["district", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingSectionData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "section_name",
                    models.CharField(
                        choices=[
                            ("personal_info", "Personal Information"),
                            ("employment_details", "Employment Details"),
                            ("i9_form", "I-9 Form"),
                            ("tax_withholdings", "Tax Withholdings"),
                            ("payment_method", "Payment Method"),
                            ("time_off", "Time Off"),
                            ("deductions", "Deductions"),
                            ("emergency_contact", "Emergency Contact"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "section_index",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                ("form_data", models.JSONField(default=dict)),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_admin",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("admin_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_comments", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_data",
                        to="onboarding.onboardingcandidate",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        help_text="School district this section data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_section_data",
                        to="core.schooldistrict",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_section_data",
                "ordering": ["district", "section_index"],
            },
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(
                fields=["district", "status"], name="onboarding__distric_2404d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(
                fields=["district", "name"], name="onboarding__distric_9df01b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(
                fields=["district", "email"], name="onboarding__distric_5c61b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(
                fields=["district", "start_date"], name="onboarding__distric_8f0567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(
                fields=["access_token"], name="onboarding__access__8dfc75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(fields=["email"], name="onboarding__email_a9310a_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingcandidate",
            index=models.Index(fields=["status"], name="onboarding__status_da7753_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingauditlog",
            index=models.Index(
                fields=["district", "candidate"], name="onboarding__distric_105fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingauditlog",
            index=models.Index(
                fields=["district", "action"], name="onboarding__distric_7632d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingauditlog",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="onboarding__candida_1be226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingdocument",
            index=models.Index(
                fields=["district", "candidate"], name="onboarding__distric_3869ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingdocument",
            index=models.Index(
                fields=["district", "document_type"],
                name="onboarding__distric_3634e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingdocument",
            index=models.Index(
                fields=["district", "verified"], name="onboarding__distric_39e37a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingemaillog",
            index=models.Index(
                fields=["district", "candidate"], name="onboarding__distric_6f4744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingemaillog",
            index=models.Index(
                fields=["district", "email_type"], name="onboarding__distric_01214e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingemaillog",
            index=models.Index(
                fields=["district", "sent"], name="onboarding__distric_58c70e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingemaillog",
            index=models.Index(
                fields=["district", "failed"], name="onboarding__distric_c83c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsectiondata",
            index=models.Index(
                fields=["district", "candidate"], name="onboarding__distric_6398a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsectiondata",
            index=models.Index(
                fields=["district", "section_name"],
                name="onboarding__distric_9c8fbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsectiondata",
            index=models.Index(
                fields=["district", "is_completed"],
                name="onboarding__distric_681994_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsectiondata",
            index=models.Index(
                fields=["district", "reviewed_by_admin"],
                name="onboarding__distric_c3b9a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsectiondata",
            index=models.Index(
                fields=["candidate", "section_index"],
                name="onboarding__candida_78a68b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="onboardingsectiondata",
            unique_together={("candidate", "section_name")},
        ),
    ]
