# Generated by Django 5.2 on 2025-11-12 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolDistrict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="District display name", max_length=200, unique=True
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code for district (e.g., 'district1', 'nyc-schools')",
                        unique=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Primary contact email", max_length=254
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="District-specific configuration (JSON)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School District",
                "verbose_name_plural": "School Districts",
                "db_table": "school_districts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="school_dist_code_950fdf_idx"),
                    models.Index(
                        fields=["is_active", "name"],
                        name="school_dist_is_acti_c15c9c_idx",
                    ),
                ],
            },
        ),
    ]
