export const INTERVIEW_STATUSES = {
  SCHEDULED: 'Scheduled',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  NO_SHOW: 'No Show',
} as const;

export type InterviewStatus = typeof INTERVIEW_STATUSES[keyof typeof INTERVIEW_STATUSES];

export const INTERVIEW_STATUS_OPTIONS = [
  INTERVIEW_STATUSES.SCHEDULED,
  INTERVIEW_STATUSES.COMPLETED,
  INTERVIEW_STATUSES.CANCELLED,
  INTERVIEW_STATUSES.NO_SHOW,
] as const;

export const INTERVIEW_DATE_FILTERS = {
  ALL: 'All Dates',
  TODAY: 'Today',
  THIS_WEEK: 'This Week',
  THIS_MONTH: 'This Month',
  UPCOMING: 'Upcoming',
  PAST: 'Past Interviews',
} as const;

export const INTERVIEW_DATE_FILTER_OPTIONS = [
  INTERVIEW_DATE_FILTERS.ALL,
  INTERVIEW_DATE_FILTERS.TODAY,
  INTERVIEW_DATE_FILTERS.THIS_WEEK,
  INTERVIEW_DATE_FILTERS.THIS_MONTH,
  INTERVIEW_DATE_FILTERS.UPCOMING,
  INTERVIEW_DATE_FILTERS.PAST,
] as const;
