export const SCREENING_CATEGORIES = {
  ALL: 'all',
  CERTIFICATION: 'certification',
  EXPERIENCE: 'experience',
  SKILLS: 'skills',
  AVAILABILITY: 'availability',
  GENERAL: 'general',
} as const;

export type ScreeningCategory = typeof SCREENING_CATEGORIES[keyof typeof SCREENING_CATEGORIES];

export const SCREENING_CATEGORY_OPTIONS = [
  SCREENING_CATEGORIES.ALL,
  SCREENING_CATEGORIES.CERTIFICATION,
  SCREENING_CATEGORIES.EXPERIENCE,
  SCREENING_CATEGORIES.SKILLS,
  SCREENING_CATEGORIES.AVAILABILITY,
  SCREENING_CATEGORIES.GENERAL,
] as const;

export const SCREENING_CATEGORY_LABELS: Record<ScreeningCategory, string> = {
  [SCREENING_CATEGORIES.ALL]: 'All Categories',
  [SCREENING_CATEGORIES.CERTIFICATION]: 'Certification',
  [SCREENING_CATEGORIES.EXPERIENCE]: 'Experience',
  [SCREENING_CATEGORIES.SKILLS]: 'Skills',
  [SCREENING_CATEGORIES.AVAILABILITY]: 'Availability',
  [SCREENING_CATEGORIES.GENERAL]: 'General',
};
